### ISSUE TITLE
Cursor position changes when formatting

### ISSUE THREAD

**Issue by moshiwu** [yieldmo/uncrustifier#12]
Hope:**cursor stays in its original position before format.**

I format my code frequently so I need to return to the previous position manually every time.

Thanks for your working.This extension helpful for me!

**Comment by harquail** [comment]
thanks @moshiwu -- this seems like a bug.  It's worth noting that the desired cursor position will change due to formatting changes, so this is something we'll want to keep in mind when fixing it

**Comment by harquail** [comment]
Here's the relevant line: https://github.com/yieldmo/uncrustifier/blob/master/Uncrustify/SourceEditorCommand.swift#L72
