### ISSUE TITLE
Install extension permanently

### ISSUE THREAD

**Issue by benrudhart** [yieldmo/uncrustifier#4]
Hi,

two questions:
- do you know how to install and run the extension permanently (not only in debug mode)?
- did you find an option to auto-format the current file (e.g. when it is saved or the project gets built?)

**Comment by harquail** [comment]
- Yep — you install the extension with the app target (Uncrustifier, not Uncrustify).  Right now this is a blank app, an obvious next step would be to add a UI here for choosing the uncrustify.cfg file.  I'll update the readme.
- I haven't found a way to do this through an extension — XCode gives you a text buffer when your command is invoked, but does not invoke the command on save or build.
