### ISSUE TITLE
add UI for choosing custom config file

### ISSUE THREAD

**Issue by harquail** [yieldmo/uncrustifier#7]

**Comment by tylerjames** [comment]
Is there a way to edit the current config file?

**Comment by harquail** [comment]
You should be able to change the configuration file without rebuilding by overwriting Uncrustifier.app/Contents/PlugIns/Uncrustify.appex/Contents/Resources/uncrustify.cfg

Obviously this isn't ideal, which is what this issue is for

**Comment by tylerjames** [comment]
No problem, not ideal but at least it's doable. Thanks

**Comment by gdorion** [comment]
Hi,
Nice extension :-) !
Most people want to have that file shared with their team in the git repository of their project. Meaning that you could select a repository (not only a single file) and automatically find all the .uncrustify files in it.

Thanks a ton !

Guillaume.

**Comment by harquail** [comment]
Hey @gdorion: that's a reasonable request, but I think separate from this feature.  Can you open another issue for it?  Thanks!

**Comment by gdorion** [comment]
Hey @harquail,
I will. Thanks.

**Comment by harquail** [comment]
![low-res-wireframe](https://cloud.githubusercontent.com/assets/6343948/19868812/1d7d855a-9f80-11e6-83eb-264190517aae.jpg)

**Comment by gdorion** [comment]
:-) ! Let me know if I can help.

**Comment by harquail** [comment]
I'm going to work on implementing this in the next couple of days — I'll link the branch here as soon as I start.  Feedback welcome on the super quick mockup haha.

Proposed functionality:
Choose a cfg file — Either from a few popular choice (eg. NYT, Airbnb) or add a custom config file.  The path will be show in the UI if a custom config file was selected.  It can be added by selecting "custom".  Info button shows information on how to create a cfg file.

Link at the bottom of the window to this repo on github.

**Comment by harquail** [comment]
Also welcome are any suggestions for good pre-set cfg files to include

**Comment by harquail** [comment]
https://github.com/yieldmo/uncrustifier/tree/choosy-ui
